### ISSUE TITLE
TypeCollections don't have an `add` method.

### ISSUE THREAD

**Issue by startling** [jvoorhis/ruby-llvm#14]
``` ruby
module.types.add("integer", LLVM::Int)
```

gives me 

`undefined method 'add' for #<LLVM::Module::TypeCollection:0x000001009f3958> (NoMethodError)`.

The `[]=` method [tries to call the method, too](https://github.com/jvoorhis/ruby-llvm/blob/master/lib/llvm/core/module.rb#L64), and gets the same error.

**Comment by jvoorhis** [comment]
Good catch. Git tells me it's my fault. I'll write a test and patch this weekend.

**Comment by startling** [comment]
thanks!

**Comment by whitequark** [comment]
I've addressed this in #23 .

**Comment by jvoorhis** [comment]
@whitequark Thanks! As you can tell, ruby-llvm is due for some updates and a fresh release. If anyone is interested in helping me push out the latest bits, please email me at jvoorhis at gmail dot com.

**Comment by whitequark** [comment]
ruby-llvm is central for one of my projects, so I'm willing to update it. I'm currently working on compat with latest JRuby.

**Comment by jvoorhis** [comment]
I've been considering moving the project into a Github organization and opening up development to the community. Would you find that valuable?

**Comment by whitequark** [comment]
That would be awesome.

**Comment by whitequark** [comment]
I see you've created the organization. How would the submission process look like? I see that @ishikawa has already committed some of his changes.

**Comment by jvoorhis** [comment]
The process is a work in progress, but my intent is to make the project's long-term contributors committers.

I've just merged ruby-llvm/ruby-llvm#1. Sending pull requests against ruby-llvm/ruby-llvm master seems like a good way to go. It also seems like a good time to revive the Google Group to discuss the release process.

**Comment by whitequark** [comment]
Oh, there is a Google Group?

I would suggest using GitHub issues for discussing. They have email interoperability of Google Groups, but allow to keep all the information in one place.

**Comment by jvoorhis** [comment]
Also a good idea. I'll look into setting that up.

**Comment by jvoorhis** [comment]
I just created ruby-llvm/ruby-llvm#5 to discuss collaboration.
