### ISSUE TITLE
LLVM::Module.parse_bitcode does not dispose the memory buffer

### ISSUE THREAD

**Issue by whitequark** [jvoorhis/ruby-llvm#21]
I don't see the temporary MemoryBuffer destroyed anywhere. It probably should get a finalizer registered.

Besides, this seems to be a problem with basically all classes.

**Comment by jvoorhis** [comment]
After reviewing the code, I agree this does seem problematic. A finalizer could do the job, but my preference would be to release the buffer explicitly as soon as it's no longer needed. Thanks for catching this!

**Comment by whitequark** [comment]
I agree that it is best to release the buffer explicitly when possible. The current implementation of `dispose` already allows that.
